modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/BrassAmber-Mods/soulbound-armory"
license = "undefined"

[[mods]]
modId = "soulboundarmory"
version = "0VERSION" # FML wants a leading digit here.
displayName = "soulbound armory"
description = """RPG-style equipment inspired by old Better Dungeons' "Soul" weapons"""
